name: BUILD
on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ✅
        uses: actions/checkout@v3

      - name: 'install angular'
        run: npm install -g @angular/cli@16.1.0

      - name: 'install dependencies'
        run: npm install

      - name: 'build angular' 
        run: ng build --base-href /angular-observable-pattern/

      - name: 'Deploy 🚀'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/angular-observable-pattern
          branch: gh-pages
          clean: true
